env:
  global:
    secure: jAmSfrEv4EaGFYHbbFy+3DGkOUx2AYLRSIzRu4goRs/cXT4EgJo5TrJ52Pc6R4JE2tCor5NzyPDW9O1L0gHLkjK7CYTd6xgNNX2X8wJ673/SqwDSznYj13ssjOLlbyClau95t1ixjZQyy+f97bAasr6Aq9QZcyTaUqrefjNXN/GO+x9t3xA86hLvHNOWRWGVNcTQBBkib7fvb/0OLjrbrSM8amT/Sp13T5IIyZYJv2JxKFBD84belOF5cm2he9gb1ym015scgiMbg5DsPLUyMcLKy1HUQCssFepmyhpfRGP1Ei1MIu4LOaq9Mn81SAFLhb1YBVkvL6wtI/C0x4jARiS7gEfs2vfCcSzaS/ryx6cgf7fwOqsejjAWxFYrOexjFXw3xO4zs9YTNONqr+I28gkk8VtuH93/e5+bG8rsNKhbNiDMb2WfDG2Vfq4Tmc6sk6A5b0Z49DjJtQUrbTloSbyG1tpr9djWk1HLVFpkkC6hsVajDxXJqKK2D17QRVP2p9IxaYGtIkbEeM3+2DV2tXvsF/WLniyRThY03I8csfqZm2d+q8pBFwALYGMSfeDifff3UqctLedBFbB3RENFRZq4N+939Jpk3r0k2/PPBo+sTY7ZQojxR1cD9rqPdI0eRoxlR0Ab648ovbcNbvMcAd0RHuk3dugLt27x4BHXVW0=
language: python
python: '3.6'
services:
- docker
script:
- "./.ci/step_00.sh"
- "./.ci/check_01.sh"
- "./.ci/check_02.sh"
- "./.ci/check_03.sh"
- "./.ci/check_04.sh"
- "./.ci/step_99.sh"
