version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Prepare the machine to run the checks
          command: .ci/step_00.sh
      - run:
          name: PEP-8 compliance
          command: .ci/check_01.sh
