FROM dexbase
COPY Test/ae /proj/src/ae
# Normally, this ENV below is not required but it is for the exercise
ENV DAWGIE_DOCKERIZED_AE_GIT_REVISION="FAKE-VERSION-FOR-EXERCISE"
ENV PYTHONPATH=/proj/src
ENTRYPOINT [ "python", "-m", "dawgie.pl", "-L", "logging.INFO" ]
