name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  CI-Initialize:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          architecture: 'x64'
          python-version: '3.12'
      - name: Intialize Environment
        run: |
          python -m pip install --upgrade pip
          pip install -r Python/requirements.txt
          pip install -r .ci/requirements.txt
       - name: Coding Style
        run: black --check --diff -l 160 --skip-string-normalization Python Test
