name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout
      - name: Install Python
        uses: actions/setup-python
        with:
          architecture: 'x64'
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Python/requirements.txt
          pip install -r .ci/requirements.txt 
      - name: Code Style
        run: black --check -l 160 -s .
