name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  CI-Actions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Python/requirements.txt
          pip install -r .ci/requirements.txt 
      - name: Code Style
        run: black --check -l 160 -s .
